function center_coord_filter=multiresSTFT3(ck_idx,center_coord_filter,sizeH,FIR,L,v1,v2,p1,p2,c1,c2,delta,numRefinement,T)

for i=1:size(ck_idx,1)
    
%     minck1=center_coord_filter(i,1);
%     minck2=center_coord_filter(i,2);
    cw1=center_coord_filter(i,1);
    cw2=center_coord_filter(i,2);
    
    sizeH2=sizeH;

    ck = ck_idx(i);
    ck_bck=ck;
    
    v1p=v1;
    v2p=v2;
    p1p=p1;
    p2p=p2;
    c1p=c1;
    c2p=c2;
    
    for j=1:numRefinement
        
        sizeH2 = sizeH2/2;
        
        %[w_ori,scale,~]=getSTFTfilter(FIR,L,sizeH2,delta);
         
        F=rectwin(sizeH2);
        w_ori = [zeros(1,L),F'];
        w_ori = circshift(w_ori,sizeH2/2);
        scale = (1/sum(F));
        
        
        v1p=v1p(sizeH2+1:end);
        v2p=v2p(sizeH2/2+1:end-sizeH2/2);
        p1p=p1p(sizeH2+1:end);
        p2p=p2p(sizeH2/2+1:end-sizeH2/2);
        c1p=c1p(sizeH2+1:end);
        c2p=c2p(sizeH2/2+1:end-sizeH2/2);
        
%         cw1 = minck1;
%         cw2 = minck2;
        cw1 = cw1-sizeH2/2;
        cw2 = cw2-sizeH2/2;
        
        ck_bck=ck_bck-sizeH2/2;
        ck=mod(ck_bck,L+sizeH2);
        
        
%         [minck1,minck2] = refine_coords_block3(...
%             cw1,...
%             cw2,...
%             ck,...
%             L,...
%             v1p,...
%             v2p,...
%             p1p,...
%             p2p,...
%             c1p,...
%             c2p,...
%             sizeH2,...
%             w_ori,...
%             scale,...
%             T);

        [cw1,cw2] = refine_coords_block3(...
            cw1,...
            cw2,...
            ck,...
            L,...
            v1p,...
            v2p,...
            p1p,...
            p2p,...
            c1p,...
            c2p,...
            sizeH2,...
            w_ori,...
            scale,...
            T);
        
        
        %xxx=1;
        
    end
    
    %center_coord_filter(i,:)=[minck1,minck2];
    center_coord_filter(i,:)=[cw1-sizeH2/2,cw2-sizeH2/2];
    
end