function [out_block_i_path,...
    out_block_i_lk,...
    out_block_i_coord,...
    out_block_j_path,...
    out_block_j_lk,...
    out_block_j_coord,...
    flag_all_resolved]=resolve_2_blocks(in_block_i_path,...
    in_block_i_lk,...
    in_block_i_coord,...
    in_block_j_path,...
    in_block_j_lk,...
    in_block_j_coord)

a1=in_block_i_coord(1);
b1=in_block_i_coord(2);
a2=in_block_i_coord(3);
b2=in_block_i_coord(4);

c1=in_block_j_coord(1);
d1=in_block_j_coord(2);
c2=in_block_j_coord(3);
d2=in_block_j_coord(4);
%%
% - linea - pixel
% - solo quadrati?
code1=region2code(a1,b1,c1,d1);
code2=region2code(a2,b2,c2,d2);
type=overlap_table(code1,code2);
%%
[   out_block_i_path,...
    out_block_i_lk,...
    out_block_i_coord,...
    out_block_j_path,...
    out_block_j_lk,...
    out_block_j_coord,...
    flag_all_resolved]=resolve_overlap2(...
    type,...
    a1,b1,a2,b2,c1,d1,c2,d2,...
    in_block_i_path,...
    in_block_i_lk,...
    in_block_i_coord,...
    in_block_j_path,...
    in_block_j_lk,...
    in_block_j_coord);
